### ISSUE TITLE
Feature request - undo button

### ISSUE THREAD

**Issue by martinstoeckli** [martinstoeckli/SilentNotes#100]
It would be convenient to have an undo-button in the note editor, so that unindentionally typed characters are easier to correct.

**Comment by martinstoeckli** [comment]
I'm thinking about replacing the current editor with [ProseMirror](https://prosemirror.net/), because this editor would offer more features and seems more future proof. An undo button will be considered when the decision about the editor is done.

**Comment by smord6** [comment]
I know this isn't exactly the same, but an undo button if a check list item is deleted would be nice. 

Or maybe make the trash icon only visible on a long press.

I can create a separate issue if you want. Thanks

**Comment by martinstoeckli** [comment]
@smord6 - Yes actually this _is_ the same, because the paper bin button just searches for the current paragraph and deletes it. Even if it looks different it is only a convenience function and does the same as you would do by using the back button.

**Comment by martinstoeckli** [comment]
Implemented in version 7.2.0
