### ISSUE TITLE
Problem scrolling beyond the ends of text & index list

### ISSUE THREAD

**Issue by uli-on** [martinstoeckli/SilentNotes#105]
Steps to reproduce

- Open a note with enough text to make the page scrollable, twice the screen height and more.
- Slide the text upward so you arrive at the very bottom of it.
- Slide upwards one more time to make sure the text can't be moved upward any more.
- After an – imagined – break, you might've forgotten where in the note you are. 
- Begin reading again and drag upward.
Result: The page doesn't move, you will be at the bottom already. 
- Slide your finger back downward, not lifting it. Now the page doesn't move downward either (like the app froze in the meantime). 
- You can repeat that sliding up and down, without any success. 
- Until you lift your finger and your first slide is in the *correct*, the *downward*, direction.

Same is valid for the upper end of the text, sliding directions switched of course, and also for the index page.

Technical corner stones: 
- SilentNotes 5.8.1
- Android 6.0.1 (with GPS 21.18.16) EDIT: non-rooted, no nothing
- Webview 92.0.4515.159
- Moto G4

**Comment by martinstoeckli** [comment]
Thanks a lot for the detailed reproduction steps, I can reproduce this and it is indeed a strange behaviour. There is probably not much one can do about it though, even when loading a simple HTML page like the info dialog (without any JS) the WebView acts like this, nonetheless I will do some more testing about it.

**Comment by martinstoeckli** [comment]
With version 8.x the tech stack changed to Blazor/Hybrid, which interacts differently with the WebView. I close this issue, should the problem still occur it can be reopened.
