### ISSUE TITLE
Cannot connect to NextCloud with LetsEncrypt SSL certificate

### ISSUE THREAD

**Issue by martinstoeckli** [martinstoeckli/SilentNotes#111]
I got the report that SilentNotes on Android devices cannot connect to NextCloud instances anymore, even when they worked before and no settings have changed meanwhile (Windows installations are not affected). After some debugging and research I found out that this is caused by the LetsEncrypt SSL certificate, for an indepth explanation see:
  https://github.com/xamarin/xamarin-android/issues/6351#issuecomment-945646088

In short:
Since September 29th 2021 the "DST Root CA X3" certificate expired, it was used by LetsEncrypt, so older devices/os/libraries which do not know about LetsEncrypt's own root certificate, can validate the certificate anyway.

**Workaround:**
A workaround was implemenented, so that NextCloud users can connect to their NextCloud instance, even if the issue can currently not be solved in a satisfying way (scroll down to https://github.com/martinstoeckli/SilentNotes/issues/111#issuecomment-1095028982 for more information). WebDav connections now have a new option to accept invalid certificates, this allows to connect to NextCloud and /e/ cloud services. Unsafe SSL connections are not recommended, but since the content is always end-to-end encrypted anyway, it is justifiable.

**Comment by martinstoeckli** [comment]
There is a workaround which can be used, but it is not a final solution and cannot be built in into SilentNotes. You can do it on your own risk, should you encounter problems in other apps it is possible to reactivate it any time.

Navigate to the Android settings:
`Settings/Security & location/Advanced/Encryption & Credentials/Trusted credentials`

Deactivate this old root certificate:
`Digital Signature Trust Co.`

![Screenshot_1636365504](https://user-images.githubusercontent.com/7747113/140728959-fcec05ce-d581-4ef0-a172-d5c608d712b9.png)

**Comment by martinstoeckli** [comment]
It seems that the problem can be overcome by switching the HttpClient to the native Android implementation: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows , this will be considered for the next version of SilentNotes.

**Comment by martinstoeckli** [comment]
A workaround was built in, but the issue is kept open, for when the development environment allows to solve the issue properly.

**Comment by pkoevesdi** [comment]
I couldn't connect via SSL to my nextcloud server too, _nor a generic Apache WebDAV server_. Of course, both work in other apps and web browser. Neither the builtin workaround nor the workaround [here](https://github.com/martinstoeckli/SilentNotes/issues/111#issuecomment-963029608) solve it. I'm stuck because I don't get any meaningful error message, see #174.

**Comment by martinstoeckli** [comment]
@pkoevesdi - Instead of the workaround it should now be possible to tick the option "Accept unsafe certificates".

It depends on your configuration what the url looks like, to get more information you can setup a WebDav connection with Windows Explorer (not Internet Explorer) if you have this OS available. The same credentials should work with SilentNotes too.

**Comment by pkoevesdi** [comment]
I'm aware of the "Accept unsafe certificates", which was also classified as a workaround here. But as said, on my generic webdav both workarounds work, on my nextcloud none.

So, I seem to have a different problem there, sorry for looking for support here, maybe, with the knowledge now, it shows up as the wrong place.

I can connect to nextcloud via webdav, which is the url `example.com/nextcloud/remote.php/dav/files/USERNAME/`
But there are also apps out there, which connect to `example.com/nextcloud` and then offer me the nextcloud content to choose the location from.
Of which type is silentnotes?
If of first type (connecting to the long webdav-URL), as I assume from Your last comment, then, what is the difference between choosing "webdav" or "nextcloud" connection?

**Comment by martinstoeckli** [comment]
On a test account I had to use an url of this form: https://example.com/nextcloud/remote.php/dav/files/USERNAME maybe in your case it could be just http:// .

There is no diference, the "Nextcloud WebDav" connection was only added to make it more recognizeable, so a user can find it easier.

If the problem persists and you can access the path with other tools, I would be interested in a test account, I would then try to debug the problem.

**Comment by martinstoeckli** [comment]
Finally found a workaround for this issue, it allows to use the native Android HttpClient which has no issues with the certificate.

The native Android HttpClient by default uses the underlying Java class `HttpURLConnection`, which does not allow to send custom http methods like `PROPFIND` which are required for WebDav. The workaround now makes use of the `SocketsHttpHandler` for this specific request on Android.

**Comment by martinstoeckli** [comment]
Workaround: On Android the default HttpClientHandler uses the underlying Java class "HttpURLConnection", which unfortunately cannot handle the http method "PROPFIND".

So we make an expection for this single request and use the "SocketsHttpHandler" which has its own implementation, though it cannot validate SSL certificates from LetsEncrypt. We can safely ignore the validation, because consecutive calls will do the validation with the Android implementation.

**Comment by martinstoeckli** [comment]
Finally solved this issue in version 8.0.0, see description above.
