### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by Dizzap** [martinstoeckli/SilentNotes#112]
As discussed via email  - I'll add Czech translation.

**Comment by Dizzap** [comment]
I checked out how the Turkish localization was done and if I'm not mistaken, I need to create a new file under `src/Localization` with the name of `Lng.SilentNotes.cz` and translate the strings. And then add it to `SilentNotes.UWP.csproj`.
Is that correct @martinstoeckli ?

**Comment by martinstoeckli** [comment]
Exactly, and add a reference to the Android project too. Add it as reference, so it does not make a copy of the file to the project directory.
