### ISSUE TITLE
Issue & PR templates

### ISSUE THREAD

**Issue by Dizzap** [martinstoeckli/SilentNotes#120]
I'd like to suggest adding templates for Issues and Pull requests (PR) to the repository. It's fairly easy and it could help with issues created by "random" people. I mean it more as a guide on "what should I write here" and "did I forget something...?" rather than a strict rule.  However the amount of issues created here is close to none, so I wouldn't be surprised if you didn't want to waste your time with it.
I can put together some samples if you'd like.

Couple handy resources:
- [How to add issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)  
- [How to add PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [Some sample templates](https://github.com/stevemao/github-issue-templates/)

Cheers,
Jakub

**Comment by martinstoeckli** [comment]
Finally found the time to add those templates. Additionally I also created new [contribution guidelines](CONTRIBUTING.md).
