### ISSUE TITLE
Russian language is missing in the UI

### ISSUE THREAD

**Issue by tommynok** [martinstoeckli/SilentNotes#133]
**Describe the bug**
   Russian language is missing in the user interface.
Two different devices, OS MM and Oreo. System language - Russian.
   Also there is a problem with displaying icons (only Oreo device)

**Platform (please complete the following information):**

 - Android 6.0.1 and 8.1.0
---------------------------------------------------------------
Screenshots 

![photo_2021-12-18_00-53-42](https://user-images.githubusercontent.com/69355171/146647490-e693dfe2-e43a-4e44-af36-d642618de60a.jpg)
![photo_2021-12-18_00-51-03](https://user-images.githubusercontent.com/69355171/146647491-0d79ea6e-a63c-42ea-8f44-5ab109b77517.jpg)

**Comment by martinstoeckli** [comment]
Indeed, it should have been included, but somehow it is missing. I will soon create a new release containing the Russian and the Chinese language resources (hope I can do it next week).

**Comment by martinstoeckli** [comment]
I'm a bit at a loss about the icons, they are SVG graphics in an HTML page, displayed by Androids WebView. Do you have a special standard browser installed, which replaces the Chrome WebView?

**Comment by tommynok** [comment]
> Indeed, it should have been included, but somehow it is missing. I will soon create a new release containing the Russian and the Chinese language resources (hope I can do it next week).

Ah, I see. The Russian language is in the changelog, but it is not yet in the resources.

**Comment by tommynok** [comment]
> SVG graphics in an HTML page, displayed by Androids WebView. Do you have a special standard browser installed, which replaces the Chrome WebView?

On both devices, Google Chrome was removed.
I have updated AndroidWebView on Oreo device. And the icons are displayed correctly.
Although WebView was very "fresh", the same version as on the MM device.
In any case, it seems that the problem is solved)

**Comment by martinstoeckli** [comment]
Wanted to let you know that version 6.0.3 is available from the store.
