### ISSUE TITLE
Unable to sync on phone with Nextcloud WebDAV

### ISSUE THREAD

**Issue by EdoSecco** [martinstoeckli/SilentNotes#136]
**Describe the bug**
I have an account on Wölkli Nextcloud; while on Windows I managed to set the synchronization of SilentNotes via WebDAV without any problem, there is no way to set on my phone, the app is last version, taken from IzzyOnDroid, I inserted the very same [URL](https://ppp.woelkli.com/remote.php/webdav/)/user/pw but always get the message "not possible to sync with cloud, try later" it's two days now :-D
I have other things on the phone synced with that Nextcloud instance so I don't think it's caused by this, and before I had SN on Dropbox and it went well.

**Platform (please complete the following information):**
 - OS: Android 8, Samsung A5 2017

**Comment by martinstoeckli** [comment]
Could you double check the URL for backslash characters, because those could work on Windows but Unix systems need slash characters? Also be aware that the Url could be case sensitive and require correct upper and lower case characters.

**Comment by martinstoeckli** [comment]
Since it seems to be a NextCloud installation and the Windows installation is working, you should also have a look at this open issue #111 . There is a workaround but I cannot solve it in the app right now.

**Comment by EdoSecco** [comment]
> could you have a look at this open issue #111 ? There is a workaround

Very sorry I didn't notice that issue; many thanks, now it works!

**Comment by martinstoeckli** [comment]
No problem, glad it works now.
