### ISSUE TITLE
Feature request - Recycle bin

### ISSUE THREAD

**Issue by MrNessuno** [martinstoeckli/SilentNotes#137]
Is it possible to have a recycle bin for deleted notes? There is no way right now to recover a note if I missclick the delete button on a note.
If not a recycle bin maybe change the delete method to be less missclickable.
Thank you

**Comment by martinstoeckli** [comment]
Actually the recycle bin already exists, you can list all deleted notes by expanding the 3-dot menu and choose "Open recycle bin".

![Icon](fastlane/metadata/android/en-US/images/phoneScreenshots/302-safe-open-menu.png)
