### ISSUE TITLE
Cursor not following word

### ISSUE THREAD

**Issue by stephenhawk8054** [martinstoeckli/SilentNotes#143]
**Describe the bug**
I'm not sure what's wrong but when I type in `Code block`, the cursor still stays at beginning of the line before first letter. It follows next letters normally.

The words become like these:

```
home -> omeh
git -> itg
```

Video:

[https://pixeldrain.com/u/5PDZLbhn](https://pixeldrain.com/u/5PDZLbhn)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version: 6.0.3

**Comment by martinstoeckli** [comment]
Thanks for the precise description of the bug and the video. I can reproduce the behaviour, sometimes the currently used editor has some glitches, like this similar issue #79 . This is why I will soon try to switch to [prosemirror](https://prosemirror.net/) for editing, some first tests indicate that it works more stable.

**Comment by martinstoeckli** [comment]
This issue will be solved in version 7.0 which is currently in the testing phase.

**Comment by martinstoeckli** [comment]
Just published [version 7.0.0](https://github.com/martinstoeckli/SilentNotes/releases/tag/v7.0.0) which solves this issue.
