### ISSUE TITLE
Keyboard closes due to synchronization (Android)

### ISSUE THREAD

**Issue by Sekt0rX** [martinstoeckli/SilentNotes#155]
Hi, thanks for the app, it suits my needs well except for the below issue:

If I open SilentNotes, go into an existing note and start typing BEFORE the online Syncronization is complete, it will close the keyboard as im typing, this happens right at the moment the pop-up message is displayed "Successfully syncronized notes".

This happens 7/10 for me, I'm usually half way through a sentance. I'm using OneDrive to Sync.

Alternatively, if I open SilentNotes, go into an existing note and tap to bring the keyboard up and just wait without typing anything the "Successfully syncronized notes" pop-up appears over the keyboard without closing it (although I cant click through to begin typing until the pop-up disappears).

**Platform (please complete the following information):**
 - OS: Android (11) on a Samsung Galaxy S10

**Additional context**
Tested with multiple keyboards; AnySoft Keyboard, FlorisBoard; both have the same issue.

IF the cause is simply the ""Successfully syncronized notes" pop-up itself, I personally would be happy with a Settings option to disable the Success pop-up entirely (but still be notified if a failure with the Sync does occur).

Thanks.

**Comment by martinstoeckli** [comment]
Thanks for writing. The reolad of the page is actually only done when the repository looks different after the synchronization than before. Now I can imagine that by typing before the synch has finished, the repository indeed looks different, but I have to test it out to be sure what happens. If this is the case, a list of notes with merged content could be built and only if this exact note was modified the refresh is necessary. This won't be easily done, but it seems possible.

**Comment by martinstoeckli** [comment]
It looks as if there are some edge cases, when the pending synchronization can interfere with the proper storage of the modifications. When closing the app immediately after editing, the previous content will be shown the next time the app is reopened.

**Comment by martinstoeckli** [comment]
Version 8.x switched to Blazor WASM, therefore the GUI had to be completely reimplemented. I will close this issue, but you can reopen it, should this still be a problem.
