### ISSUE TITLE
[Bug] Wrong page height when the label selector is expanded

### ISSUE THREAD

**Issue by kytrun** [martinstoeckli/SilentNotes#190]
**Describe the bug**

![GIF 2022-10-21 15-42-40](https://user-images.githubusercontent.com/32519285/197141147-139f87e0-853b-4af8-8498-bd8ead8ec071.gif)

**Platform (please complete the following information):**
 - OS: [Windows]

**Comment by martinstoeckli** [comment]
Thank you for reporting. Do I get it right, that the scrolling happens only because you are using the mouse wheel, would the input field stay in place otherwise?

**Comment by kytrun** [comment]
Hey @martinstoeckli, I have uploaded the gif of the whole window.

**Comment by martinstoeckli** [comment]
Thank you for the gif, but does the up/down scrolling happen automatically when the text field gets the focus, or do you scroll it manually to show that the size is too large?

**Comment by kytrun** [comment]
That's just scrolling manually.🤣

**Comment by martinstoeckli** [comment]
Version 8.x switched to Blazor WASM, therefore the GUI had to be completely reimplemented. I will close this issue, but you can reopen it, should this still be a problem.
