### ISSUE TITLE
Turkish short_description is too long

### ISSUE THREAD

**Issue by IzzySoft** [martinstoeckli/SilentNotes#197]
Fastlane's `short_description.txt` is limited to 80 chars. Your Turkish one currently has 123 chars and thus is truncated on import (in the middle of a word). Can you please fix that?

I don't speak Turkish so I cannot tell for sure, but here is what Deepl gives me on a shorter one that fits by its length:

> Bilgisayarınıza isteğe bağlı uçtan uca şifreli senkronizasyon ile not alma

**Comment by martinstoeckli** [comment]
Hi Alp, this seems to be best solved by you, could you have a look at it? Thanks!

**Comment by sakci** [comment]
Ah, my bad.

Then, the new short description should be:

`Uçtan uca şifreleme ve bilgisayara eşitleme destekli not alma uygulaması.`

**Comment by IzzySoft** [comment]
Great, thanks! Just updated here manually for now so it will be fixed with the next sync at 7 pm UTC already (instead of waiting for the next release).
