### ISSUE TITLE
Add support for local backup

### ISSUE THREAD

**Issue by HarriBuh** [martinstoeckli/SilentNotes#207]
**Describe the solution you'd like**
I'm sure this has been issued before, but why does the app not support local backups on your device at all?

I do not wish to setup an online dav storage, and I'm used to backup my files on my phone, encrypt it by myself and then _maybe_ upload it to a host of my choice

**Comment by martinstoeckli** [comment]
Yes this is not the first time somebody asked for a local backup and it is somewhat related to https://github.com/martinstoeckli/SilentNotes/issues/96 . It would be a good feature to have and nothing speaks against an implementation, there are just other features with higher priority.

One thing that would have to be solved is, when a user has a synchronization in place and wants to restore a backup, then the sync would immediately overwrite the loaded backup (the notes of the backup will usually be older).

In the meantime one can setup a local WebDav instance in the private network, e.g. with a local NextCloud/OwnCloud instance. This has even the advantage that multiple devices can synchronize the notes. Anyway, thank you for writing the suggestion.
