### ISSUE TITLE
[X] Splash Screen at StartUp

### ISSUE THREAD

**Issue by juanpc2018** [martinstoeckli/SilentNotes#219]
Android:
Option in settings to Enable or Disable Splash Screen at Startup
purpose: speed boot time.

Splash screen is nice the 1st time, but after 3 times it should Disable Automatically.

**Comment by martinstoeckli** [comment]
Thanks for writing, but the splash screen does not slow down the startup, there is no idle waiting, in the background the application does the initialization and loading of the notes. So while one could remove the splash screen, it would not lead to a better experience.
