### ISSUE TITLE
WEBDAV doesn't work on android13

### ISSUE THREAD

**Issue by suppergit** [martinstoeckli/SilentNotes#244]
**Describe the bug**
If you found a bug, you can file an issue, please make sure that you updated to the newest version of SilentNotes and include a much information as you can about the problem (but leave out sensitive data like passwords!). If possible, add a description that helps to reproduce the problem.
➽ If the problem is related to online synchronization, then a test account on the online storage service can be a huge help.

**Platform (please complete the following information):**
 - OS: [e.g. Android, Windows, Kindle]
WEBDAV doesn't work on android13, but work on android10.
**Additional context**
![1713198880372](https://github.com/martinstoeckli/SilentNotes/assets/73597691/acaef9f6-d03e-441a-a14c-8ac03b8e1040)
![1713198880375](https://github.com/martinstoeckli/SilentNotes/assets/73597691/925afec2-2131-4c3e-bf99-4671d16d1655)

**Comment by martinstoeckli** [comment]
Thank you for reporting. Could you check whether this workaround solves your problem? https://github.com/martinstoeckli/SilentNotes/issues/111

If yes, this should be resolved in the upcoming version 8.0.

**Comment by suppergit** [comment]
> Thank you for reporting. Could you check whether this workaround solves your problem? #111
> 
> If yes, this should be resolved in the upcoming version 8.0.

Yes, It works now with this workaound.
