### ISSUE TITLE
Does not recognize other languages/Spellcheck enabled in English.

### ISSUE THREAD

**Issue by giseledute** [martinstoeckli/SilentNotes#254]
**Describe the bug**
The software's spellcheck is always on in English, indicating any words in other languages ​​as wrong. I write in Portuguese and although this is not a big problem, the red lines under all the words are a bit annoying.

**Platform (please complete the following information):** Windows

**Additional context**
I noticed that this problem doesn't occur on Android.
Exemple:
![image](https://github.com/user-attachments/assets/98e4bee1-30c8-4358-8364-bf24d5573324)

**Comment by martinstoeckli** [comment]
Thank you for reporting. The auto correction is actually part of the OS (Windows in this case), there is no code inside the app to do this. So it depends on the language settings in Windows, but I would have to test it out, which setting exactly configures the language of the auto correction.

**Comment by martinstoeckli** [comment]
Added a workaround, so that the WebView2 uses the current user language. This solves the problem with the auto-correction.

**Comment by martinstoeckli** [comment]
Solved with 8.0.2.
