### ISSUE TITLE
Unable to open application after update 8.0 (in Windows Store/Windows10)

### ISSUE THREAD

**Issue by asasn** [martinstoeckli/SilentNotes#256]
**Describe the bug**

Unable to launch the application, no response after double clicking the mouse.
The same is true after rebooting the computer.
Updated in the Windows App Store.（Windows10）
The icon has changed.
![QQ_1722220628182](https://github.com/user-attachments/assets/de7c7ff7-ab6d-4dfa-b9a2-dfc99272dc4f)

---

**Follow-up: Surprisingly easy!!** Upgrade the system from Windows10 1909 version to 22H2. 
Without upgrading Win11!
I thought I needed to upgrade Win11 at first, in fact, I did not need to, by comparing different versions of multiple machines, I finally determined that Win10 22H2 version can be used!
The first time you try it, it may not have been removed cleanly, causing it to fail to install in the app Store.
Then I tried to reboot again and install again, and finally succeeded.
But for some reason, the data seems to have been lost. Fortunately, I have a backup on webdav, which was successfully solved by pulling it to the local.

**Comment by PrashantUnity** [comment]
It Opening Fine for me WIndows 11

https://github.com/user-attachments/assets/b4a75b1a-32f2-4188-a1fc-5e4206b2edec

**Comment by martinstoeckli** [comment]
The application just doesn't start up? May I ask what Windows version you have installed?

I had problems like that when I began to port the application to Maui/Blazor and downloaded the first test packages from the Microsoft store, but could overcome them with the CI build script. I wonder whether something is missing in the installer bundle, maybe from the sdk: https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ .

**Comment by asasn** [comment]
@martinstoeckli 
Windows version is Win10 1909……I think the problem may be in the sdk, my edge is new.

![QQ_1722302108105](https://github.com/user-attachments/assets/bef71d7b-9c1c-4a89-be8f-fad0f09c292d)

My original SDK was derived from optional components of visual studio
Its version number is only 10.0.22...
![QQ_1722302187369](https://github.com/user-attachments/assets/fc0410ab-0b0e-4942-885b-638027040015)

Now I try to download it and replace it with a new one
Windows 11 SDK (10.0.26100.0)

**Comment by martinstoeckli** [comment]
The minimum target framework is 10.0.17763.0 (also known as version 1809 October 2018) and the store should offer the installation only to supported Windows versions. The package is self-contained, what explains its big size, it should theoretically contain anything which is necessary to run.

It is build for the windows10.0.19041.0 and actually installing this SDK should not be necessary, it is just a thought to find the root of the problem.

**Comment by suppergit** [comment]
has the same issue at win10 19044.1288

**Comment by asasn** [comment]
@martinstoeckli 
I still haven't solved this problem for the time being. I have tried many other ways besides reinstalling the Windows10 system. 
I was very lucky to keep the old msi installation package, and I rolled back the version.
Maybe you can offer the previous version for people who have the same problem to download.
See if it can use the 8+ version in the next update

**Comment by martinstoeckli** [comment]
@asasn - I will see what I can do with the build process, whether I can target another sdk, but I will need to test it before releasing. Would you like to participate in that test (because I cannot find out on my systems if the problem still persists)? If so, you could send me the e-mail address you use to login to the Microsoft store, then I could add you to the test team.

**Comment by asasn** [comment]
@martinstoeckli Add `_` after `as`, then the mail domain is `qq.com`... I'm sorry, the trouble is to prevent robots from grabbing it.
I don't know what to do next, wait for your notification and download and install from the store?

**Comment by martinstoeckli** [comment]
@asasn - Oh I didn't mean that you publish it here, thought you would send me an e-mail. You can delete the comment, so your e-mail doesn't leak.

Yes as soon as I'm ready I will send you a notification and you should be able to update to the test version. But before that I will have to find a quiet minute and read throught the documents, make the changes, build the test release and upload it to the store. It will take some time, this is a spare time project after all and free time is a rare good.

**Comment by martinstoeckli** [comment]
Thought about what I can do about the problem and before I start trying with tweaking the build process, I implemented a page which displays error information. The new version 8.0.4 should soon be available in the store, it is published for all (no test version).

The error page allows to copy the last exception and offers to backup the repository. So there is a chance that after updating the error is shown in this dialog, it depends on how early the error happens and whether the app is able to show the error page at this moment.

**Comment by asasn** [comment]
@martinstoeckli 
**Just tried it and the feedback is code: 0x80240438**
By the way, I don't know why, when I use webdav synchronization (version 7.32), if I use v2rayN and other technologies, the synchronization will fail, but in fact, if I choose a domestic non-proxy, the same webdav synchronization of other software will not fail. Only it will be affected.

**Comment by martinstoeckli** [comment]
@asasn - Could you be a bit more specific, is there a dialog which shows the error message, the stack trace and a button to export the repository? Could you send me the error-message and the stack-trace per e-mail, if one is available, or a screenshot if not?

**Comment by asasn** [comment]
@martinstoeckli **Does not show. Nothing works without feedback.** 
I just saw it code: 0x80240438
Maybe the mistake happened earlier?

**Comment by martinstoeckli** [comment]
@asasn - I just created a test package for the Windows store (version is 8.0.5) and included you to the test group, so you should be able to install it soon.

Error 0x80240438 is often mentioned in context of a failed Windows store installation, so it could be helpful to first uninstall SilentNotes completely from the Windows machine and reboot before the installation. Just make sure you still have the notes and the transfercode on the Android device.

After rereading the documentation I came to the conclusion, that the target OS framework should not have an impact on the binaries, it is just a way to check when features are used, which are not yet available in older Windows versions. What I did was to update to the newest Maui/Asp libraries and to simplify the build script.

@suppergit - win10 19044.1288 was published in october 2021, can I assume that you explicitely want to keep this old version? Otherwise it may help to let Windows update itself.

**Comment by martinstoeckli** [comment]
Was informed that updating to Windows 22H2 solved the problem, thanks for testing!
