### ISSUE TITLE
The program cannot be started.

### ISSUE THREAD

**Issue by gioxouly** [martinstoeckli/SilentNotes#281]
The program won't start, which seems to have happened the day before yesterday after a minor update patch for windows.

Now I want to know what to do. I have a lot of notes that are encrypted. I would like to know where the data of the notes are saved in the computer.

SilentNotes 8.2.0.0

AMD Ryzen 7 5800X
RAM	16.0 GB
x64
Windows 10 Home
22H2
OS 19045.5011
Windows Feature Experience Pack 1000.19060.1000.0

**Comment by martinstoeckli** [comment]
The repository is stored in this directory:
  C:\Users\<username>\AppData\Local\Packages\22846MartinStoeckli.SilentNotes_4aa5zt7h99ppe\LocalState

If you want to try to reinstall the app, do a backup of the file "silentnotes_repository.silentnotes" before you deinstall the app.

**Comment by gioxouly** [comment]
> The repository is stored in this directory: C:\Users<username>\AppData\Local\Packages\22846MartinStoeckli.SilentNotes_4aa5zt7h99ppe\LocalState
> 
> If you want to try to reinstall the app, do a backup of the file "silentnotes_repository.silentnotes" before you deinstall the app. Do you see anything when starting the app, or does it never show a window at all?

Thanks. The window never appears at all, but can be seen briefly in the task manager for about 0.5 seconds after a few seconds of clicking on the application icon.

**Comment by gioxouly** [comment]
I checked in the system settings and found that the system could still be updated, and after that it could be opened normally.
OS 19045.5131

**Comment by martinstoeckli** [comment]
Thank you for getting back, I'm glad that it is working again.

**Comment by OgreTransporter** [comment]
I have the same problem. Reinstalling did not help me. I have now compiled it myself - then it works. But not from the MS Store.

**Comment by martinstoeckli** [comment]
@OgreTransporter - It was indeed difficult to build the release upload msixbundle, it can't be done in VisualStudio anymore, I had to write a Github action. So I don't build locally in release mode for publishing. You can also download the installer from SilentNotes homepage (just updated it to version 8.2.0) if you have troubles with the store.
