### ISSUE TITLE
cannot start SilentNotes

### ISSUE THREAD

**Issue by medicalfreak** [martinstoeckli/SilentNotes#282]
I cannot start SilentNotes anymore, even though is was downloaded and installed properly by MS Store.
It worked for months & years for me - after a win update it did not react anymore.

I did unintall it by WinKey+i, I re-downloaded it, pressed Install and the ribbon in MS Store says 'Open', however, nothing will happen.
Also Win Update with KB5046714 which was mentioned in a forum when encounter MS Store install/download problems did not help.
MS Store cache was cleared too.

I also tried do sideload the bundle with no effect.

Any idea? Thanks so much

SilentNotes 8.2.0.0
Microsoft Windows [Version 10.0.19045.5198]

**Comment by martinstoeckli** [comment]
Possibly related to #281 .

**Comment by martinstoeckli** [comment]
Could you check whether there are some pending updates for Windows?

**Comment by medicalfreak** [comment]
I read #281 but looks like the solution mentioned was compiling from scratch at the end. No idea, how to do this.
There are no pending updates for Win10.

**Comment by medicalfreak** [comment]
Installing pending updates did not help. 
A tool called 'Store_Apps_repair_tool' did the job finally by fising/re-installing the store.
Thanks again@martinstoeckli for your support !

**Comment by medicalfreak** [comment]
Use of 'Store_Apps_repair_tool' fixed the MS store

**Comment by martinstoeckli** [comment]
Thank you very much for your research and for telling about the found solution! So at least it is not the fault of the build process, but nevertheless hard to explain to other users. I will keep it in mind should the problem pop up in future.
