### ISSUE TITLE
Wrong code message on other devices

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [martinstoeckli/SilentNotes#36]
I try to add another android phone or windows app but I got always wrong code or mismatched version message.

I use gmx.com as storage.
Any idea?

**Comment by martinstoeckli** [comment]
This should be no problem, both devices need SilentNotes v4.0.0 though. Older versions won't be able to open the repository, because it is now compressed before synchronization.

**Comment by sorryusernameisalreadytaken** [comment]
hey, thx for the reply.

Jep, both had the same version. Can you give me the older version as apk, I can not find them.
So I can try the v3.

**Comment by martinstoeckli** [comment]
Each version is backwards compatible to all previous versions, so the newest v4.0.0 should be able to read all existing repositories. Earlier versions (e.g. 3.3.0) cannot read repositories if they where once synchronized with a newer version (4.0.0).

So the easiest way to get compatible is to update SilentNotes on all devices to v4.0.0 this should solve your problem. If this is not possible/wanted, then you can manually delete the repository from the cloud storage and do a fresh sync form each device (the notes are stored locally and won't get lost). The disadvantage is, that the same problem happens again, as soon as one device is updated to a newer version as the others.

**Comment by sorryusernameisalreadytaken** [comment]
The both devices had 100% the same apk installed. Can I send you logs?

**Comment by martinstoeckli** [comment]
Ok, but which version? Can you update to 4.0.0? Was it once synchronized with 4.0.0?

**Comment by sorryusernameisalreadytaken** [comment]
Perhaps the use is the error but I dont find the problem.

Both are version v4.0.0. One is installed from f-droid the other from google:play.

okay, I did that once but I did it again. I delete now the **silentnotes_repository.silentnotes** in the gmx.com cloud. Then I reset all the android-app storage and reinstall both apps.

The results is the same.
Can you tell me the 100% correct formst of the transfercode?
The message after creating the repo the first time show it with **-** and later it will displyed with **spaces**. What is the best format. I always try all kinds of. E.g.: 
xxXa-Hwsq-Qthgt-Affe
xxXaHwsqQthgtAffe
xxXa Hwsq Qthgt Affe

**Comment by martinstoeckli** [comment]
You wrote that both installed versions are 4.0.0 so this indicates a real problem (spaces and hyphens are handled automatically). So I wrote some more tests and indeed can confirm that there is a bug reading the transfercode. I will publish a new version which should fix this problem. Many thanks for pointing it out.

**Comment by martinstoeckli** [comment]
Fixed with version 4.0.1.
