### ISSUE TITLE
Collaboration / Sharing notebooks or notes

### ISSUE THREAD

**Issue by alexanderadam** [martinstoeckli/SilentNotes#53]
Sali Martin,

I know that this could be a tough one but it would be nice to have some kind of collaboration between two or more users. For example for having grocery lists or similar things.

**Comment by martinstoeckli** [comment]
Originally I wanted to have a neat littel tool for my private notes, it was never meant for sharing information with other people. I'm sorry, but I would like to keep it simple, other tools may be better fitted for this kind of task.
