### ISSUE TITLE
Problem using sync with  nextcloud/Dav server

### ISSUE THREAD

**Issue by talk2g** [martinstoeckli/SilentNotes#61]
Gives an error " could not sync notes with cloud,please try later"

**Comment by martinstoeckli** [comment]
What did you try already, can you e.g. connect to the WebDav directory with the Windows Explorer? Are you working with the Windows or Android app? Can you check whether you can access the directory with other tools?

**Comment by talk2g** [comment]
Sorry for the incomplete bits..
1) its the android version
2) yes i m using my nextcloud server with Davx right  now
3) its hosted on a third party server (ppp.woelkli.com)
4) as soon as i fill in tje details amd press 'connect', it gives the error.
I can provide some logs and screenshots if u want.

**Comment by martinstoeckli** [comment]
You are using the woelkli cloud, that's fine, I wanted to try it out myself anyway. It seems they offer a free account, so I will test it out. Thanks for the informations.

**Comment by talk2g** [comment]
Thanks, hope to see it working soon..😁

**Comment by martinstoeckli** [comment]
So I made a test with woelkli cloud and it worked perfectly with WebDav. This is what I did:

1. Choose WebDAV as cloud storage.
2. Enter https://cloud.woelkli.com/remote.php/webdav/ as URL and your credentials. If you have a Pro account, use this url instead: https://pro.woelkli.com/remote.php/webdav/ .

Additionally I logged in to the woelkli website and created a subdirectory "SilentNotes" and used this url: https://cloud.woelkli.com/remote.php/webdav/SilentNotes , this worked as well. What I found out is, that the URL is case sensitive, so https://cloud.woelkli.com/remote.php/webdav/silentnotes didn't work for the directory "SilentNotes".

**Comment by talk2g** [comment]
After entering the https://cloud.woelkli.com/remote.php/webdav/ url and credentials, its giving me this
"Check ur username and password and check if u have privileges on the server"
What format username did u use
Abc@xyz.com or abc@xyz.com@woelkli.com

**Comment by martinstoeckli** [comment]
I used the same credentials as I need to login to their [website](https://woelkli.com), in my case this was my private e-mail address.

**Comment by talk2g** [comment]
nope,i still cant get it to work, asks me to check username and password and the server privileges.

**Comment by martinstoeckli** [comment]
That's strange, I would have to be able to debug this. If you want you can contact me per email (homepage), then I can send you my credentials for further testing.

**Comment by talk2g** [comment]
Thanks, just sent a message on your email .

**Comment by talk2g** [comment]
Fix-
check which domain u have an acc on 
https://ppp.woelkli.com -if u made acc thru nextcloud, then this may be the case

or 
https://cloud.woelkli.com
idf u made acc directly thru woelkli website

use the url accordingly
https://cloud.woelkli.com/remote.php/webdav/- for the latter 
and https://ppp.woelkli.com/remote.php/webdav/- for the earlier

you can also make custom folders/path (case sensitive)
as suggested by 
@martinstoeckli  above.

lastly huge thx to martin for helping me out personally
