### ISSUE TITLE
Pressing return on Android does not move cursor to new line.

### ISSUE THREAD

**Issue by martinstoeckli** [martinstoeckli/SilentNotes#79]
On some Android devices, when pressing <return> the cursor does not move to the next line, even if a new line was added to the text. This behaviour started end of 2020 after an update of the GBoard app.

**Comment by martinstoeckli** [comment]
This error was caused by the "Android System WebView" and is not related to SilentNotes. The update from 06.01.2021 of the "Android System WebView" component, available in the playstore, solved this issue.

**Comment by martinstoeckli** [comment]
Seems it is a combination of the WebView component and the Android Gboard. Only on Android 10 with standard keyboard.

**Comment by martinstoeckli** [comment]
The problem can be reproduced if a "normal" character is the last character before the cursor, as soon as there is special character like a space or comma, the line break works as expected. The same I can reproduce not only with the Quill editor, the problem also exists e.g. with the slate editor.

**Comment by martinstoeckli** [comment]
Filed an issue on: https://issuetracker.google.com/issues/177757645

**Comment by gitzila** [comment]
Also happens with Android 11, webview 91.0.4472.164 (447216434) and gboard 10.8.06.382062350-beta-arm64-v8a (60781002).

**Comment by martinstoeckli** [comment]
I'm currently trying to replace the editor with [ProseMirror](https://prosemirror.net/), which can work around this issue.
The work is done in the [branch feture/prose-mirror](https://github.com/martinstoeckli/SilentNotes/tree/feature/prose-mirror).

**Comment by martinstoeckli** [comment]
It seems that Google also has fixed the issue on Jan 2023, see https://issuetracker.google.com/issues/177757645#comment21
