### ISSUE TITLE
won't accept transfer code

### ISSUE THREAD

**Issue by pelicanbadger** [martinstoeckli/SilentNotes#95]
Installed Windows 10 app.  Installed latest Android app.
During setup, a pop-up showed the "transfer code", including hyphens.
Wrote it down.
Selected Google Drive as the cloud storage.
Setting up the Android app, clicked on "synchronize notes" button, right hand corner,
in android app.  App now asks for Transfer code.
In the windows app, click on "show transfer code":  it shows the same transfer code
that was displayed earlier, but without the hyphens.
Anyway: on the android app, where it now says "enter the transfer code...",
I've entered it 3 times: once with the hyphens (per the earlier notification window displayed
during the setup process), once
without the hyphens, using spaces instead, exactly as shown in the Windows app, and once
without hyphens or spaces (just in case...), and, every time, I get the following note at the bottom of the
android screen, when I tap "continue":

"Please check the transfer code for typos, and use the
latest version of SilentNotes"

Again, typed it perfectly, with spaces, and with hyphens instead of spaces, with no typos,
in the latest version of the program.   

Can't get past the "continue" step.

Pls advise.  Thanks.

**Comment by martinstoeckli** [comment]
Thank you for reporting. The hyphens are optional, they are stripped away if entered, so are blanks. Important is, that the code is case sensitive, so please make sure the letters are typed lower and upper case. There are two situations coming to my mind which could lead to this problem:

1. One of the installations is not the newest one, could you please double check in the information dialog that both (Android and Windows) have version 5.7.0?
2. They point to different online repositories, as unlikely as it sounds, could check in the settings dialog, that they indeed point to the same location?

**Comment by martinstoeckli** [comment]
Just made a commit, with a unified representation of the transfer code, so the hyphens should disappear in future versions.

**Comment by pelicanbadger** [comment]
Followed your suggestions (thanks for the quick response...!). Yes, current versions are in place, and repositories match.
Rebooted, tried again, typing in the transfer code with no blanks or hyphens, and now it works fine.
Thanks again!
