### ISSUE TITLE
Note color isn't displayed with dark mode

### ISSUE THREAD

**Issue by MrNessuno** [martinstoeckli/SilentNotes#99]
I tested the app with the dark mode since the beginning and the color of the note disappear after I close the note.
Switching to light mode all colors reappear and works normally.
Switching again to dark mode hide colors again. 
Is this intentional because of dark mode? In this case a switch to allow color would be appreciated.

**Comment by martinstoeckli** [comment]
Such a switch already exists, you can find it in the settings, it is called "Same color for all notes in dark mode". If you uncheck this option, you should see the individual colors even in dark mode. The reason for this switch is, that users which prefer the dark mode often don't like bright elements in the user interface, but don't want to loose the color information of the notes.
